#!/usr/bin/env python3
"""
Azure OpenAI security auditor.

Consumes security artifacts generated by the reusable workflows, extracts a
compact finding set, asks Azure OpenAI for a structured triage report, and
produces:
  - VULNERABILITIES.json
  - REPORTE_IA_SEGURIDAD.md
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple
from urllib.parse import urlsplit, urlunsplit

try:
    from openai import OpenAI
except ImportError:
    print("ERROR: openai package not available. Run: pip install -U openai")
    sys.exit(1)


RAW_TO_FINAL_SEVERITY = {
    "CRITICAL": "CRITICO",
    "HIGH": "ALTO",
    "MEDIUM": "MEDIO",
    "LOW": "BAJO",
    "ERROR": "ALTO",
    "WARNING": "MEDIO",
    "WARN": "MEDIO",
    "NOTE": "BAJO",
    "INFO": "BAJO",
    "0": "BAJO",
    "1": "BAJO",
    "2": "MEDIO",
    "3": "ALTO",
    "4": "CRITICO",
}

SEVERITY_RANK = {
    "CRITICO": 0,
    "ALTO": 1,
    "MEDIO": 2,
    "BAJO": 3,
}

AUTO_FIX_SAFE_TOOLS = {"Dependabot", "Snyk", "Trivy"}
MAX_FINDINGS_FOR_MODEL = 200

VULNERABILITY_RESPONSE_FORMAT = {
    "type": "json_schema",
    "json_schema": {
        "name": "security_audit_report",
        "strict": True,
        "schema": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "timestamp": {"type": "string"},
                "vulnerabilidades": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "id": {"type": "string"},
                            "archivo": {"type": "string"},
                            "linea": {"type": "integer"},
                            "severidad": {
                                "type": "string",
                                "enum": ["CRITICO", "ALTO", "MEDIO", "BAJO"],
                            },
                            "herramienta": {
                                "type": "string",
                                "enum": [
                                    "Semgrep",
                                    "CodeQL",
                                    "Snyk",
                                    "Trivy",
                                    "ZAP",
                                    "TruffleHog",
                                    "Dependabot",
                                ],
                            },
                            "regla": {"type": "string"},
                            "titulo": {"type": "string"},
                            "descripcion": {"type": "string"},
                            "impacto": {"type": "string"},
                            "explotabilidad": {"type": "string"},
                            "solucion": {"type": "string"},
                            "codigo_vulnerable": {"type": "string"},
                            "codigo_corregido": {"type": "string"},
                        },
                        "required": [
                            "id",
                            "archivo",
                            "linea",
                            "severidad",
                            "herramienta",
                            "regla",
                            "titulo",
                            "descripcion",
                            "impacto",
                            "explotabilidad",
                            "solucion",
                            "codigo_vulnerable",
                            "codigo_corregido",
                        ],
                    },
                },
                "resumen": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "total": {"type": "integer"},
                        "criticos": {"type": "integer"},
                        "altos": {"type": "integer"},
                        "medios": {"type": "integer"},
                        "bajos": {"type": "integer"},
                    },
                    "required": ["total", "criticos", "altos", "medios", "bajos"],
                },
                "can_auto_fix": {"type": "boolean"},
                "veredicto": {
                    "type": "string",
                    "enum": ["RECHAZADO", "ADVERTENCIA", "ACEPTADO"],
                },
            },
            "required": [
                "timestamp",
                "vulnerabilidades",
                "resumen",
                "can_auto_fix",
                "veredicto",
            ],
        },
    },
}


def _is_truthy(value: Any) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def _normalize_base_url(endpoint: str) -> str:
    parsed = urlsplit(endpoint.strip())
    if not parsed.scheme or not parsed.netloc:
        raise RuntimeError(
            "AZURE_OPENAI_PDF_ENDPOINT must be a full URL, for example "
            "https://<resource>.openai.azure.com/"
        )

    path = parsed.path.rstrip("/")
    if "/openai/deployments/" in path:
        path = path.split("/openai/deployments/", 1)[0]

    if path.endswith("/openai/v1"):
        normalized_path = path + "/"
    elif path.endswith("/openai"):
        normalized_path = path + "/v1/"
    elif path.endswith("/v1"):
        normalized_path = path + "/"
    else:
        normalized_path = path + "/openai/v1/"

    return urlunsplit((parsed.scheme, parsed.netloc, normalized_path, "", ""))


def _normalize_severity(value: Any, default: str = "MEDIO") -> str:
    raw = str(value or "").strip().upper()
    if not raw:
        return default
    for key, normalized in RAW_TO_FINAL_SEVERITY.items():
        if raw == key or key in raw:
            return normalized
    return default


def _severity_sort_key(finding: Dict[str, Any]) -> Tuple[int, str, str, int]:
    severity = _normalize_severity(finding.get("raw_severity"))
    return (
        SEVERITY_RANK.get(severity, 99),
        str(finding.get("tool", "")),
        str(finding.get("location", "")),
        _safe_int(finding.get("line")),
    )


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _load_json_lines(path: Path) -> List[Dict[str, Any]]:
    entries: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            entries.append(json.loads(line))
    return entries


def _stringify(value: Any) -> str:
    if value is None:
        return "N/A"
    if isinstance(value, str):
        return value.strip() or "N/A"
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def _push_finding(
    findings: List[Dict[str, Any]],
    seen: set,
    *,
    tool: str,
    rule: str,
    title: str,
    description: str,
    location: str,
    line: int,
    raw_severity: str,
    evidence: str,
    recommendation: str,
) -> None:
    dedupe_key = (
        tool,
        rule,
        title,
        location,
        line,
        _normalize_severity(raw_severity),
    )
    if dedupe_key in seen:
        return

    seen.add(dedupe_key)
    findings.append(
        {
            "tool": tool,
            "rule": rule or "N/A",
            "title": title or "Hallazgo de seguridad",
            "description": description or "Sin descripcion adicional.",
            "location": location or "N/A",
            "line": _safe_int(line),
            "raw_severity": raw_severity or "MEDIUM",
            "severity": _normalize_severity(raw_severity),
            "evidence": evidence or "N/A",
            "recommendation": recommendation or "Revisar y corregir el hallazgo.",
        }
    )


def _parse_generic_sarif(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    data = _load_json(path)
    for run in data.get("runs", []):
        driver = run.get("tool", {}).get("driver", {})
        tool_name = driver.get("name", "CodeQL")
        rules_index = {}
        for rule in driver.get("rules", []) or []:
            rule_id = rule.get("id")
            if rule_id:
                rules_index[rule_id] = rule

        for result in run.get("results", []) or []:
            rule_id = result.get("ruleId", "N/A")
            rule_meta = rules_index.get(rule_id, {})
            locations = result.get("locations", []) or [{}]
            phys = locations[0].get("physicalLocation", {}) if locations else {}
            location = phys.get("artifactLocation", {}).get("uri", "N/A")
            line = phys.get("region", {}).get("startLine", 0)
            title = result.get("message", {}).get("text") or rule_meta.get(
                "shortDescription", {}
            ).get("text")
            description = result.get("message", {}).get("text") or rule_meta.get(
                "fullDescription", {}
            ).get("text")
            recommendation = rule_meta.get("help", {}).get("text", "N/A")

            _push_finding(
                findings,
                seen,
                tool=tool_name,
                rule=rule_id,
                title=title or rule_id,
                description=description or "Hallazgo SARIF",
                location=location,
                line=line,
                raw_severity=result.get("level", "warning"),
                evidence=_stringify(result.get("partialFingerprints") or result),
                recommendation=recommendation,
            )


def _parse_semgrep_json(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    data = _load_json(path)
    for result in data.get("results", []) or []:
        extra = result.get("extra", {})
        metadata = extra.get("metadata", {})
        _push_finding(
            findings,
            seen,
            tool="Semgrep",
            rule=result.get("check_id", "N/A"),
            title=extra.get("message") or result.get("check_id", "Semgrep finding"),
            description=extra.get("message")
            or metadata.get("shortlink")
            or "Hallazgo detectado por Semgrep.",
            location=result.get("path", "N/A"),
            line=_safe_int(result.get("start", {}).get("line")),
            raw_severity=extra.get("severity", "WARNING"),
            evidence=_stringify(extra.get("lines") or metadata.get("cwe")),
            recommendation=_stringify(
                metadata.get("fix")
                or metadata.get("source")
                or metadata.get("references")
                or "Aplicar la remediacion sugerida por la regla."
            ),
        )


def _parse_snyk_json(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    data = _load_json(path)
    for vuln in data.get("vulnerabilities", []) or []:
        package_name = vuln.get("packageName") or vuln.get("name") or "dependency"
        fixed_in = vuln.get("nearestFixedInVersion") or vuln.get("fixedIn")
        recommendation = "Actualizar la dependencia vulnerable."
        if fixed_in:
            recommendation = f"Actualizar {package_name} a una version corregida: {fixed_in}"

        evidence = {
            "package": package_name,
            "version": vuln.get("version"),
            "from": vuln.get("from"),
            "upgradePath": vuln.get("upgradePath"),
            "fixedIn": fixed_in,
        }

        _push_finding(
            findings,
            seen,
            tool="Snyk",
            rule=vuln.get("id", "N/A"),
            title=vuln.get("title") or f"Dependencia vulnerable: {package_name}",
            description=vuln.get("description")
            or vuln.get("title")
            or "Vulnerabilidad en dependencia detectada por Snyk.",
            location="pom.xml",
            line=0,
            raw_severity=vuln.get("severity", "medium"),
            evidence=_stringify(evidence),
            recommendation=recommendation,
        )


def _parse_trivy_json(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    data = _load_json(path)
    for result in data.get("Results", []) or []:
        target = result.get("Target", "container-image")
        for vuln in result.get("Vulnerabilities") or []:
            package_name = vuln.get("PkgName", "package")
            fixed_in = vuln.get("FixedVersion") or "N/A"
            _push_finding(
                findings,
                seen,
                tool="Trivy",
                rule=vuln.get("VulnerabilityID", "N/A"),
                title=vuln.get("Title")
                or f"Vulnerabilidad en imagen para {package_name}",
                description=vuln.get("Description")
                or "Vulnerabilidad detectada en la imagen del contenedor.",
                location=target,
                line=0,
                raw_severity=vuln.get("Severity", "MEDIUM"),
                evidence=_stringify(
                    {
                        "package": package_name,
                        "installedVersion": vuln.get("InstalledVersion"),
                        "fixedVersion": fixed_in,
                    }
                ),
                recommendation=f"Actualizar {package_name} y reconstruir la imagen. FixedVersion={fixed_in}",
            )


def _parse_zap_json(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    data = _load_json(path)
    for site in data.get("site", []) or []:
        site_name = site.get("@name", "application")
        for alert in site.get("alerts", []) or []:
            instances = alert.get("instances", []) or [{}]
            first_instance = instances[0] if instances else {}
            location = first_instance.get("uri") or site_name
            evidence = {
                "confidence": alert.get("confidence"),
                "instances": instances[:3],
                "param": first_instance.get("param"),
            }
            _push_finding(
                findings,
                seen,
                tool="ZAP",
                rule=str(alert.get("pluginid", "N/A")),
                title=alert.get("name", "Hallazgo DAST"),
                description=alert.get("desc") or "Hallazgo detectado por ZAP baseline.",
                location=location,
                line=0,
                raw_severity=alert.get("riskcode", alert.get("riskdesc", "MEDIUM")),
                evidence=_stringify(evidence),
                recommendation=alert.get("solution") or "Aplicar la mitigacion sugerida por ZAP.",
            )


def _parse_trufflehog_json(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    entries = _load_json_lines(path)
    for entry in entries:
        source = entry.get("SourceMetadata", {}).get("Data", {}).get("Git", {})
        _push_finding(
            findings,
            seen,
            tool="TruffleHog",
            rule=entry.get("DetectorName", "SecretDetected"),
            title=f"Secreto potencial detectado por {entry.get('DetectorName', 'TruffleHog')}",
            description="Posible secreto expuesto en el repositorio.",
            location=source.get("file", "repository"),
            line=_safe_int(source.get("line")),
            raw_severity="CRITICAL",
            evidence=_stringify(
                {
                    "repository": entry.get("SourceName"),
                    "detector": entry.get("DetectorName"),
                    "verified": entry.get("Verified"),
                }
            ),
            recommendation="Rotar el secreto, eliminarlo del codigo y limpiar el historial si aplica.",
        )


def _parse_dependabot_json(path: Path, findings: List[Dict[str, Any]], seen: set) -> None:
    data = _load_json(path)
    alerts = data if isinstance(data, list) else []
    for alert in alerts:
        package_name = (
            alert.get("package")
            or alert.get("dependency", {}).get("package", {}).get("name")
            or "dependency"
        )
        ecosystem = (
            alert.get("ecosystem")
            or alert.get("dependency", {}).get("package", {}).get("ecosystem")
            or "unknown"
        )
        severity = alert.get("severity") or alert.get("security_advisory", {}).get(
            "severity", "medium"
        )
        cve = alert.get("cve") or alert.get("security_advisory", {}).get("cve_id") or "N/A"
        summary = alert.get("summary") or alert.get("security_advisory", {}).get(
            "summary", "Dependabot alert"
        )
        fixed_version = alert.get("fixed_version") or (
            alert.get("security_vulnerability", {})
            .get("first_patched_version", {})
            .get("identifier")
        )
        recommendation = "Actualizar la dependencia vulnerable."
        if fixed_version:
            recommendation = (
                f"Actualizar {package_name} ({ecosystem}) a la version corregida {fixed_version}."
            )

        _push_finding(
            findings,
            seen,
            tool="Dependabot",
            rule=cve,
            title=f"Dependabot alert: {package_name}",
            description=summary,
            location=f"{ecosystem}:{package_name}",
            line=0,
            raw_severity=severity,
            evidence=_stringify(
                {
                    "package": package_name,
                    "ecosystem": ecosystem,
                    "fixedVersion": fixed_version or "none",
                }
            ),
            recommendation=recommendation,
        )


def _parse_sbom_json(path: Path) -> Dict[str, Any]:
    data = _load_json(path)
    return {
        "component_count": len(data.get("components", []) or []),
        "serial_number": data.get("serialNumber", "N/A"),
        "bom_format": data.get("bomFormat", "CycloneDX"),
        "spec_version": data.get("specVersion", "N/A"),
    }


def _collect_artifacts(results_dir: Path) -> Dict[str, Any]:
    file_map: Dict[str, List[Path]] = {}
    for path in sorted(results_dir.rglob("*")):
        if path.is_file() and path.stat().st_size > 0:
            file_map.setdefault(path.name, []).append(path)

    findings: List[Dict[str, Any]] = []
    seen = set()
    metadata: Dict[str, Any] = {"inventory": {}, "processed_files": {}, "notes": []}

    preferred_handlers = [
        ("trufflehog-results.json", _parse_trufflehog_json),
        ("semgrep-results.json", _parse_semgrep_json),
        ("codeql-results.sarif", _parse_generic_sarif),
        ("snyk-results.json", _parse_snyk_json),
        ("trivy-results.json", _parse_trivy_json),
        ("zap-results.json", _parse_zap_json),
        ("dependabot-normalized.json", _parse_dependabot_json),
        ("dependabot-results.json", _parse_dependabot_json),
    ]

    processed_names = set()
    for basename, handler in preferred_handlers:
        matches = file_map.get(basename, [])
        if not matches:
            continue
        selected = sorted(matches)[0]
        if len(matches) > 1:
            metadata["notes"].append(
                f"Multiple matches for {basename}; using {selected.as_posix()}"
            )
        handler(selected, findings, seen)
        metadata["processed_files"][basename] = selected.as_posix()
        processed_names.add(basename)

    sbom_matches = file_map.get("sbom.json", [])
    if sbom_matches:
        selected = sorted(sbom_matches)[0]
        metadata["inventory"]["sbom"] = _parse_sbom_json(selected)
        metadata["processed_files"]["sbom.json"] = selected.as_posix()
        processed_names.add("sbom.json")

    for basename, matches in sorted(file_map.items()):
        if basename in processed_names:
            continue
        selected = sorted(matches)[0]
        if basename.endswith(".sarif"):
            _parse_generic_sarif(selected, findings, seen)
            metadata["processed_files"][basename] = selected.as_posix()

    findings.sort(key=_severity_sort_key)
    omitted = 0
    if len(findings) > MAX_FINDINGS_FOR_MODEL:
        omitted = len(findings) - MAX_FINDINGS_FOR_MODEL
        findings = findings[:MAX_FINDINGS_FOR_MODEL]
        metadata["notes"].append(
            f"Context truncated to {MAX_FINDINGS_FOR_MODEL} findings; omitted {omitted}."
        )

    metadata["finding_count"] = len(findings)
    metadata["omitted_findings"] = omitted
    return {"findings": findings, "metadata": metadata}


def _create_empty_report(reason: str) -> Dict[str, Any]:
    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "vulnerabilidades": [],
        "resumen": {
            "total": 0,
            "criticos": 0,
            "altos": 0,
            "medios": 0,
            "bajos": 0,
        },
        "can_auto_fix": False,
        "veredicto": "ACEPTADO",
        "_reason": reason,
    }


def _sanitize_response(data: Dict[str, Any]) -> Dict[str, Any]:
    vulnerabilities = []
    for index, vuln in enumerate(data.get("vulnerabilidades", []), start=1):
        tool = vuln.get("herramienta", "Semgrep")
        if tool not in {
            "Semgrep",
            "CodeQL",
            "Snyk",
            "Trivy",
            "ZAP",
            "TruffleHog",
            "Dependabot",
        }:
            tool = "Semgrep"

        sanitized = {
            "id": str(vuln.get("id") or f"vuln-{index:03d}"),
            "archivo": _stringify(vuln.get("archivo")),
            "linea": _safe_int(vuln.get("linea")),
            "severidad": _normalize_severity(vuln.get("severidad"), default="MEDIO"),
            "herramienta": tool,
            "regla": _stringify(vuln.get("regla")),
            "titulo": _stringify(vuln.get("titulo")),
            "descripcion": _stringify(vuln.get("descripcion")),
            "impacto": _stringify(vuln.get("impacto")),
            "explotabilidad": _stringify(vuln.get("explotabilidad")),
            "solucion": _stringify(vuln.get("solucion")),
            "codigo_vulnerable": _stringify(vuln.get("codigo_vulnerable")),
            "codigo_corregido": _stringify(vuln.get("codigo_corregido")),
        }
        vulnerabilities.append(sanitized)

    summary = {
        "total": len(vulnerabilities),
        "criticos": sum(1 for v in vulnerabilities if v["severidad"] == "CRITICO"),
        "altos": sum(1 for v in vulnerabilities if v["severidad"] == "ALTO"),
        "medios": sum(1 for v in vulnerabilities if v["severidad"] == "MEDIO"),
        "bajos": sum(1 for v in vulnerabilities if v["severidad"] == "BAJO"),
    }

    verdict = "ACEPTADO"
    if summary["criticos"] or summary["altos"]:
        verdict = "RECHAZADO"
    elif summary["medios"]:
        verdict = "ADVERTENCIA"

    ai_auto_fix = bool(data.get("can_auto_fix"))
    safe_tooling = all(v["herramienta"] in AUTO_FIX_SAFE_TOOLS for v in vulnerabilities)
    can_auto_fix = ai_auto_fix and safe_tooling and bool(vulnerabilities)

    return {
        "timestamp": _stringify(data.get("timestamp"))
        if data.get("timestamp")
        else datetime.now(timezone.utc).isoformat(),
        "vulnerabilidades": vulnerabilities,
        "resumen": summary,
        "can_auto_fix": can_auto_fix,
        "veredicto": verdict,
    }


def _create_markdown_report(report: Dict[str, Any], repo_name: str) -> str:
    summary = report["resumen"]
    lines = [
        "# Informe de Seguridad - Auditoria IA",
        "",
        f"**Fecha**: {report['timestamp']}",
        f"**Repositorio**: {repo_name}",
        "",
        "## Resumen Ejecutivo",
        "",
        "| Metrica | Cantidad |",
        "|---|---:|",
        f"| Total de vulnerabilidades | {summary['total']} |",
        f"| Criticas | {summary['criticos']} |",
        f"| Altas | {summary['altos']} |",
        f"| Medias | {summary['medios']} |",
        f"| Bajas | {summary['bajos']} |",
        "",
        f"**Veredicto**: `{report['veredicto']}`",
        "",
    ]

    if report["veredicto"] == "RECHAZADO":
        lines.append("La PR debe bloquearse hasta corregir vulnerabilidades altas o criticas.")
    elif report["veredicto"] == "ADVERTENCIA":
        lines.append("La PR requiere revision de seguridad antes del merge.")
    else:
        lines.append("No se identificaron hallazgos bloqueantes.")

    critical_or_high = [
        vuln
        for vuln in report["vulnerabilidades"]
        if vuln["severidad"] in {"CRITICO", "ALTO"}
    ]
    medium_or_low = [
        vuln
        for vuln in report["vulnerabilidades"]
        if vuln["severidad"] in {"MEDIO", "BAJO"}
    ]

    lines.extend(["", "## Vulnerabilidades Criticas y Altas", ""])
    if not critical_or_high:
        lines.append("No hay vulnerabilidades criticas o altas.")
    else:
        for vuln in critical_or_high:
            lines.extend(
                [
                    f"### {vuln['titulo']} ({vuln['severidad']})",
                    "",
                    f"- Ubicacion: `{vuln['archivo']}:{vuln['linea']}`",
                    f"- Herramienta: {vuln['herramienta']}",
                    f"- Regla: `{vuln['regla']}`",
                    f"- Descripcion: {vuln['descripcion']}",
                    f"- Impacto: {vuln['impacto']}",
                    f"- Explotabilidad: {vuln['explotabilidad']}",
                    "",
                    "Solucion propuesta:",
                    "```text",
                    vuln["solucion"],
                    "```",
                    "",
                    "Codigo vulnerable:",
                    "```text",
                    vuln["codigo_vulnerable"],
                    "```",
                    "",
                    "Codigo corregido:",
                    "```text",
                    vuln["codigo_corregido"],
                    "```",
                    "",
                ]
            )

    lines.extend(["## Vulnerabilidades Medias y Bajas", ""])
    if not medium_or_low:
        lines.append("No hay vulnerabilidades medias o bajas.")
    else:
        lines.extend(
            [
                "| Archivo | Linea | Severidad | Titulo | Herramienta |",
                "|---|---:|---|---|---|",
            ]
        )
        for vuln in medium_or_low:
            lines.append(
                f"| `{vuln['archivo']}` | {vuln['linea']} | {vuln['severidad']} "
                f"| {vuln['titulo']} | {vuln['herramienta']} |"
            )

    lines.extend(
        [
            "",
            "## Recomendaciones",
            "",
            "- Resolver de inmediato vulnerabilidades criticas.",
            "- Priorizar vulnerabilidades altas antes del merge.",
            "- Tratar dependencias vulnerables con actualizaciones verificadas.",
            "",
            "*Generado automaticamente por el auditor de Azure OpenAI.*",
            "",
        ]
    )

    return "\n".join(lines)


def _write_outputs(report: Dict[str, Any], repo_name: str) -> None:
    clean_report = dict(report)
    clean_report.pop("_reason", None)

    with open("VULNERABILITIES.json", "w", encoding="utf-8") as handle:
        json.dump(clean_report, handle, indent=2, ensure_ascii=False)

    markdown = _create_markdown_report(clean_report, repo_name)
    with open("REPORTE_IA_SEGURIDAD.md", "w", encoding="utf-8") as handle:
        handle.write(markdown)


def main() -> None:
    results_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "security-results")
    repo_name = os.environ.get("GITHUB_REPOSITORY", "N/A")
    fail_on_api_error = _is_truthy(os.environ.get("IA_FAIL_ON_API_ERROR", "false"))

    print(f"Starting Azure OpenAI audit in {results_dir}")
    print(f"Repository: {repo_name}")
    print(f"IA_FAIL_ON_API_ERROR: {fail_on_api_error}")

    if not results_dir.exists():
        print(f"WARN: Results directory not found: {results_dir}")
        report = _create_empty_report("results-directory-missing")
        _write_outputs(report, repo_name)
        sys.exit(0)

    try:
        client = OpenAI(
            base_url=_normalize_base_url(_required_env("AZURE_OPENAI_PDF_ENDPOINT")),
            api_key=_required_env("AZURE_OPENAI_PDF_API_KEY"),
        )
        deployment = _required_env("AZURE_OPENAI_PDF_DEPLOYMENT")
        api_version = os.environ.get("AZURE_OPENAI_PDF_API_VERSION", "").strip()
    except Exception as exc:
        print(f"ERROR: Azure OpenAI configuration is invalid: {exc}")
        if fail_on_api_error:
            raise
        report = _create_empty_report("azure-openai-config-error")
        _write_outputs(report, repo_name)
        sys.exit(0)

    context = _collect_artifacts(results_dir)
    findings = context["findings"]
    metadata = context["metadata"]

    print(f"Processed files: {len(metadata.get('processed_files', {}))}")
    print(f"Findings extracted for AI context: {len(findings)}")
    if api_version:
        print(f"Azure API version hint received: {api_version}")

    if not findings:
        report = _create_empty_report("no-findings")
        _write_outputs(report, repo_name)
        sys.exit(0)

    prompt = f"""
Eres un Arquitecto Senior de DevSecOps.

Analiza los hallazgos consolidados de seguridad para un proyecto Java y responde
UNICAMENTE con JSON valido que cumpla el schema solicitado.

Reglas:
1. Ubica cada vulnerabilidad con archivo y linea cuando exista evidencia.
2. Usa severidad final: CRITICO, ALTO, MEDIO o BAJO.
3. Si hay CRITICO o ALTO, el veredicto debe ser RECHAZADO.
4. Si solo hay MEDIO, el veredicto debe ser ADVERTENCIA.
5. Si solo hay BAJO o no hay hallazgos relevantes, el veredicto debe ser ACEPTADO.
6. can_auto_fix solo debe ser true si la remediacion es segura y acotada
   (por ejemplo actualizaciones de dependencias o base images), nunca para
   parches complejos de logica de negocio.
7. codigo_vulnerable y codigo_corregido deben ser breves. Si no aplica, usa "N/A".

Contexto del repositorio: {repo_name}
Metadata:
{json.dumps(metadata, indent=2, ensure_ascii=False)}

Hallazgos:
{json.dumps(findings, indent=2, ensure_ascii=False)}
"""

    try:
        response = client.chat.completions.create(
            model=deployment,
            temperature=0,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Eres un auditor de seguridad de software. Respondes solo "
                        "con JSON estricto y priorizas precision sobre exhaustividad."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            response_format=VULNERABILITY_RESPONSE_FORMAT,
        )
        response_text = response.choices[0].message.content or "{}"
        parsed = json.loads(response_text)
        report = _sanitize_response(parsed)
        _write_outputs(report, repo_name)

        print("Audit reports generated successfully.")
        print(f"Verdict: {report['veredicto']}")
        if report["veredicto"] == "RECHAZADO":
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        print(f"ERROR: Azure OpenAI audit failed: {exc}")
        if fail_on_api_error:
            raise
        report = _create_empty_report("azure-openai-runtime-error")
        _write_outputs(report, repo_name)
        sys.exit(0)


if __name__ == "__main__":
    main()
