name: "Ejecución de Auditoría de Seguridad"

on:
  push:
    branches:
      - test/pipeline
      - test/pipelines
      - 'feat/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-governance:
    permissions:
      contents: write
      packages: write
      security-events: write
      actions: read
      pull-requests: write

    uses: DevSecOps-Uni-Project/.github/.github/workflows/main-security-pipeline.yml@main
    with:
      java-version: '21'
      image-name: 'backend-ids'
      app-port: '8080'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }}
      AZURE_OPENAI_PDF_ENDPOINT: ${{ secrets.AZURE_OPENAI_PDF_ENDPOINT }}
      AZURE_OPENAI_PDF_API_KEY: ${{ secrets.AZURE_OPENAI_PDF_API_KEY }}
      AZURE_OPENAI_PDF_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_PDF_DEPLOYMENT }}
      AZURE_OPENAI_PDF_API_VERSION: ${{ secrets.AZURE_OPENAI_PDF_API_VERSION }}

      